<a href="https://colab.research.google.com/github/Bharat1992/DeepLearning/blob/master/numpy_broadcasting_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
               [1.2, 104.0, 52.0, 8.0],
               [1.8, 135.0, 99.0, 0.9]])

print(A)

cal = A.sum(axis=0)
print(cal)

#broadcasting here
#we are able to device 3x4 matrix with a row vector of 4 length

#rule (m,n) +/-* (1,n) ~~ (m,n) +/-* (m,n)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
B = np.random.randn(5) # rank 1 array
print(B)

C = np.random.randn(5,1) #column vector with 5 rows
print(C)

D = np.random.randn(1,5) # row vector with 5 columns
print(D)

[ 0.35156927  1.03869967  0.27467011  0.42447648 -0.75168848]
[[ 0.66794414]
 [ 0.35884943]
 [-0.63495065]
 [-0.86307728]
 [-0.37633864]]
[[ 0.79552101  1.00290708  0.06167303 -1.00005915 -0.3559974 ]]
